---
#
# Important: maintain correct handler order.
# Handlers are executed in the order in which they are defined
# and not in the order in which they are listed in a "notify: handler_name" statement!
#
# Restart before reload: an reload after a restart may be redundant but should not fail,
# but the other way around may fail when the impact of changes was too large for a reload.
#
- name: 'Restart firewalld service.'
  ansible.builtin.systemd:
    name: 'firewalld.service'
    state: restarted
    daemon_reload: true
  become: true
  listen: restart_firewalld

#
# Service reloads after restarts.
#
- name: 'Reload firewalld service.'
  ansible.builtin.systemd:
    name: 'firewalld.service'
    state: 'reloaded'
  become: true
  listen: reload_firewalld
...
