---
- name: 'Set hostname to inventory_hostname.'
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: 'Find SSH host keys.'
  ansible.builtin.find:
    path: "{{ ssh_host_signer_key_directory }}"
    pattern: ssh_host_*_key
  register: private_keys
  failed_when: "\"matched\" not in private_keys or private_keys.matched == 0"
  become: true

- name: 'Create local temporary directory.'
  ansible.builtin.tempfile:
    suffix: 'ssh_host_signer'
    state: directory
  delegate_to: localhost
  connection: local
  changed_when: false
  register: temporary_directory
  become: false

- name: 'Fetch public keys.'
  ansible.builtin.fetch:
    src: "{{ item.path }}.pub"
    dest: "{{ temporary_directory.path }}/public_keys/"
  with_items: "{{ private_keys.files }}"
  changed_when: false

- name: 'Fetch existing certificates.'
  ansible.builtin.fetch:
    src: "{{ item.path }}-cert.pub"
    dest: "{{ temporary_directory.path }}/existing_certificates/"
    fail_on_missing: false
  with_items: "{{ private_keys.files }}"
  changed_when: false

- name: 'Check if we have a CA private key with correct permissions.'
  ansible.builtin.file:
    path: "{{ ssh_host_signer_ca_private_key }}"
    mode: '0600'
  delegate_to: localhost
  connection: local

- name: 'Create temporary unvaulted copy of CA private key.'
  ansible.builtin.copy:
    src: "{{ ssh_host_signer_ca_private_key }}"
    dest: "{{ temporary_directory.path }}/{{ ssh_host_signer_ca_private_key | basename }}"
    mode: '0600'
    decrypt: true
  delegate_to: localhost
  connection: local
  become: false

- name: 'Sign SSH host keys.'
  ansible.builtin.command: >
    ssh-keygen -h
      -s {{ temporary_directory.path | quote }}/{{ ssh_host_signer_ca_private_key | basename | quote }}
      -P {{ ssh_host_signer_ca_private_key_pass | quote }}
      -I {{ ssh_host_signer_id | quote }}
      -n {{ ssh_host_signer_hostnames | quote }}
      "{{ temporary_directory.path }}/public_keys/{{ inventory_hostname | quote }}{{ item.path | quote }}.pub"
  with_items: "{{ private_keys.files }}"
  changed_when: false
  delegate_to: localhost
  connection: local
  no_log: true

- name: 'Find generated certificates (== signed host keys).'
  ansible.builtin.find:
    path: "{{ temporary_directory.path }}/public_keys/{{ inventory_hostname }}{{ ssh_host_signer_key_directory }}"
    pattern: 'ssh_host_*_key-cert.pub'
  delegate_to: localhost
  connection: local
  register: certificates

- name: 'Compare generated certificates to existing certificates from servers.'
  ansible.builtin.shell: |
    set -o pipefail
    diff <(ssh-keygen -L -f {{ item.path | quote }} | tail -n +2) \
         <(ssh-keygen -L -f {{ existing_certificates_dir }}/{{ item.path | basename | quote }} | tail -n +2)
  args:
    executable: '/bin/bash'
  vars:
    existing_certificates_dir: "{{ temporary_directory.path | quote }}/existing_certificates/\
                                {{ inventory_hostname | quote }}{{ ssh_host_signer_key_directory }}"
  with_items: "{{ certificates.files }}"
  changed_when: false
  failed_when: false
  delegate_to: localhost
  connection: local
  register: certificate_comparison

- name: 'Copy certificates back to server if the generated ones are different from the existing ones.'
  ansible.builtin.copy:
    src: "{{ item.item.path }}"
    dest: "{{ ssh_host_signer_key_directory }}"
    owner: root
    group: root
    mode: '0644'
  when: item.rc != 0
  with_items: "{{ certificate_comparison.results }}"
  notify: reload_sshd
  become: true

- name: 'Remove local temporary directory.'
  ansible.builtin.file:
    name: "{{ temporary_directory.path }}"
    state: absent
  delegate_to: localhost
  connection: local
  changed_when: false

- name: 'Add the signed certificates to SSH configuration file.'
  ansible.builtin.lineinfile:
    dest: "{{ ssh_host_signer_ssh_config }}"
    line: "HostCertificate {{ item.path }}-cert.pub"
    insertafter: "HostKey {{ item.path }}"
    state: present
    owner: root
    group: root
    mode: '0644'
    backup: true
  with_items: "{{ private_keys.files | selectattr('path', 'match', ssh_host_signer_key_types) | list }}"
  notify: reload_sshd
  become: true

- name: 'Remove HostKey directives from the SSH configuration file for unused ssh host key types.'
  ansible.builtin.lineinfile:
    dest: "{{ ssh_host_signer_ssh_config }}"
    line: "HostCertificate {{ item.path }}-cert.pub"
    state: absent
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ private_keys.files | rejectattr('path', 'match', ssh_host_signer_key_types) | list }}"
  notify: reload_sshd
  become: true

- name: 'Remove corresponding HostCertificate directives from the SSH configuration file for unused ssh host key types.'
  ansible.builtin.lineinfile:
    dest: "{{ ssh_host_signer_ssh_config }}"
    line: "HostKey {{ item.path }}"
    state: absent
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ private_keys.files | rejectattr('path', 'match', ssh_host_signer_key_types) | list }}"
  notify: reload_sshd
  become: true
...
