---
- name: 'Install yum-utils, which provides the "needs-restarting" utility.'
  ansible.builtin.yum:
    name: yum-utils
    state: latest
    update_cache: true
  become: true
- name: 'Update all installed packages (except Slurm).'
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: true
    exclude: 'slurm*'  # Specific Slurm versions configured in slurm-* roles, because we use a custom patched version.
  become: true
- name: 'Install cron job to reboot server regularly to activate kernel updates.'
  ansible.builtin.cron:
    name: 'Reboot to load new kernel.'
    weekday: '2'
    minute: '45'
    hour: '06'
    user: root
    job: /bin/needs-restarting -r >/dev/null 2>&1 || /sbin/shutdown -r +60 "Restarting to apply updates..."
    cron_file: reboot
  when: inventory_hostname in groups['auto_reboot'] | default([])
  become: true
...
