---
- name: create build directory
  file:
    path: /root/build_directory
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: copy Dockerfile
  copy:
    src: ./files/Dockerfile
    dest: /root/build_directory/Dockerfile
    owner: root
    group: root
    mode: '0644'
- name: build container image
  docker_image:
    name: listsrv-api:v1.0
    build:
      path: /root/build_directory
      source: build
    state: present
- name: archive container image as a tarball
  docker_image:
    name: listsrv-api:v1.0
    archive_path: /root/listsrv-api_v1_0.tar
    source: pull
    state: present
- name: fetch archived image
  fetch:
    src: /root/listsrv-api_v1_0.tar
    dest: ./listsrv-api_v1_0.tar
    flat: true    
- name: copy tarball to host
  copy:
    src: ./listsrv-api_v1_0.tar
    dest: /root/listsrv-api_v1_0.tar

- name: load container from tarball
  docker_image:
    name: listsrv-api:v1.0
    load_path: /root/listsrv-api_v1_0.tar
    state: present
    source: load
- name: Create the listsrv container
  docker_container:
    name: listsrv-api
    image: listsrv-api:1.0
    restart_policy: unless-stopped
    recreate: true
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
...
